"""empty message

Revision ID: 781de23a030a
Revises: 700b66ad1a61
Create Date: 2022-06-11 11:43:07.353426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781de23a030a'
down_revision = '700b66ad1a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
