"""empty message

Revision ID: 875dd353696f
Revises: dc276709652d
Create Date: 2022-06-12 08:44:09.436686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875dd353696f'
down_revision = 'dc276709652d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_shows_artist_id_fkey', 'artist_shows', type_='foreignkey')
    op.drop_constraint('artist_shows_show_id_fkey', 'artist_shows', type_='foreignkey')
    op.create_foreign_key(None, 'artist_shows', 'Show', ['show_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artist_shows', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_shows', type_='foreignkey')
    op.drop_constraint(None, 'artist_shows', type_='foreignkey')
    op.create_foreign_key('artist_shows_show_id_fkey', 'artist_shows', 'Show', ['show_id'], ['id'])
    op.create_foreign_key('artist_shows_artist_id_fkey', 'artist_shows', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
